### ISSUE TITLE
Improvement: Apply hard `argc` limits in every possible builtin function

### ISSUE THREAD

**Issue by vcwild** [iaurg/42-minishell#53]
Some of our built-in functions should not work over a max number of arguments.

We should protect every **possible** built-in implementation with a max argc input.
This should be enough for us to have the possibility to handle every possible input for these arguments.

Brief example:

The `cd` command should not handle more than 2 arguments. (deterministic)
The `unset` command handles a theoretical infinite amount of parameters, as long as the args 1 to inf are env variables.

**Comment by iaurg** [comment]
Do you have any tips on it? Can we set a max argc and ignore everything above this limit?

**Comment by vcwild** [comment]
I belive we can allow a global upper limit of 24 argc arguments and that should be enough, we already have a sufficient enough parser to handle other exceptions.
