### ISSUE TITLE
Find leaks in implemented commands

### ISSUE THREAD

**Issue by vcwild** [iaurg/42-minishell#80]
Run comands for every implementation with valgrind.

If you find a major bug or an inconsistency, please open an issue with its details.

TODO:
- [x] cd
- [x] env
- [x] export
- [x] unset
- [x] exit
- [x] echo
- [x] pwd
- [x] pipes
- [x] redirections:
    - [x] >
    - [x] <
    - [x] >>
    - [ ] <<

**Comment by iaurg** [comment]
Take a look on "still reachable"

```bash
==35476== HEAP SUMMARY:
==35476==     in use at exit: 204,640 bytes in 218 blocks
==35476==   total heap usage: 1,052 allocs, 834 frees, 238,818 bytes allocated
==35476== 
==35476== LEAK SUMMARY:
==35476==    definitely lost: 0 bytes in 0 blocks
==35476==    indirectly lost: 0 bytes in 0 blocks
==35476==      possibly lost: 0 bytes in 0 blocks
==35476==    still reachable: 204,640 bytes in 218 blocks
```

**Comment by iaurg** [comment]
Leaks found on heredoc << https://github.com/iaurg/42-minishell/issues/94#issuecomment-1163805074
